### PR TITLE
Fix zone testing import error

### LINKED ISSUE #268: Encounter error for npm run test after upgrading to Angular v11
**Describe the bug**

Encounter error shown below for `npm run test` after upgrading to Angular v11

image

### PR DESCRIPTION
**Pull request by NereusWB922**
### Summary:

Fixes #268 

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Move import statement of `zone.js/dist/zone-testing` to the top of `test.ts` file
- Disable tslint rule on ordered-imports for `test.ts` file

### Proposed Commit Message:

```
Fix zone-testing import error

Npm run test will break if the import statement 
for zone-testing is not at the top of test.ts file. 

Let's reorder the import statement and disable
tslint rule for test.ts file.
```

### CODE REVIEW

File: src/test.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 // This file is required by karma.conf.js and loads recursively all the .spec and framework files
-
+// tslint:disable:ordered-imports
```
Comment (Arif-Khalid) [inline src/test.ts:2]: Developers might find the reason of disabling imports not apparent.
Could you add a comment about the reason this is necessary?

**Review by Arif-Khalid — CHANGES_REQUESTED** [review]
A small and efficient way to disable a particular rule for a particular file. 
Just one small change to documentation.

File: src/test.ts (hunk 1 above)
Comment (NereusWB922) [reply src/test.ts:3]: Thanks for the suggestion! Just committed the new changes.

**Review by cheehongw — APPROVED** [review]
LGTM

**Review by Arif-Khalid — APPROVED** [review]
LGTM!
