### PR TITLE
Fix issue where tooltip does not appear for certain labels

### LINKED ISSUE #477: Tooltips do not show for some labels
**Describe the bug**
For some labels that have ellipsis, the tooltips do not show on hover.

**To Reproduce**

1. Open WATcher and choose CATcher-org/WATcher as the repo
2. Scroll to issue 82 and hover over the category.Feature label
3. Observe that the tooltip does not appear

**Expected behavior**
Tooltip appears 

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome

### PR DESCRIPTION
**Pull request by wx-03**
### Summary:

Fixes #477 

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Changed the condition to check for overflow of label

### Proposed Commit Message:

```
Fix issue where tooltips do not appear for certain labels

For some labels that have ellipsis, the tooltips do not show on 
hover. This makes it difficult for users to see the full label name.

Let's change the condition for checking for ellipsis so that the 
tooltips appear for all labels that have ellipsis.

```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [ ] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [ ] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

File: src/app/shared/issue-pr-card/issue-pr-card-labels/issue-pr-card-labels.component.ts [hunk 1]
```diff
@@ -16,10 +16,23 @@ export class IssuePrCardLabelsComponent {
...
 
+  hasOverflow(span: HTMLElement): boolean {
+    const range = document.createRange();
+    range.selectNodeContents(span);
+    const textWidth = range.getBoundingClientRect().width;
+    const containerWidth = span.getBoundingClientRect().width;
+
+    console.log('textWidth: ', textWidth);
+    console.log('containerWidth: ', containerWidth);
+    console.log('text - container: ', textWidth - containerWidth);
```
Comment (NorbertLoh) [inline src/app/shared/issue-pr-card/issue-pr-card-labels/issue-pr-card-labels.component.ts:27]: Perhaps we can remove this

**Review by NorbertLoh — CHANGES_REQUESTED** [review]
Some nits to fix. Otherwise LGTM! Tested it and it addresses the issue faced [here](https://github.com/CATcher-org/WATcher/pull/475#pullrequestreview-2779943304).

**Review by NorbertLoh — APPROVED** [review]
LGTM!
