### PR TITLE
Standardise error messages

### LINKED ISSUE #152: Inconsistent error message for invalid repository
**Describe the bug**
Using an invalid repository name (e.g. `CATcher-org/invalid-repo`) when logging into WATcher gives a different error message from using an invalid repository name when switching repositories while logged in.

**To Reproduce**

1. Launch WATcher
2. Provide an invalid repository name
3. Login and see the first error message
4. Change repository, using the same invalid repository name, and see the second error message

**Expected behavior**
The error message for invalid repositories should be consistent.

**Screenshots**
When logging into WATcher with `CATcher-org/invalid-repo`:
image

When changing repositories to `CATcher-org/invalid-repo` while logged in:
image

Additionally, the former error message doesn't seem to directly inform users that the provided repository name is invalid.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Additional context**
This issue seems to be consistently present on the initial launch of WATcher. Refreshing/logging out and entering the same invalid repository name before logging in again seems to show either error message inconsistently.

### PR DESCRIPTION
**Pull request by joyngjr**
### Summary:

Fixes #152 

Error message displayed for invalid repository names on initialisation and changing repositories are now the same. 

However, there are still some differences in behaviour between entering an invalid repository on initialisation and changing to an invalid repository. When an invalid repository name is entered on initialisation, an empty repository is created but the `label-filter-bar.component` is never loaded. On the other hand, the change to an invalid repo is rejected when users attempt to change to one, and the filter bar component doesn't seem to cause an issue. Perhaps it would be better to change the order of input validation in the future so an invalid repo can be flagged out at the login page, or we could create a default filter bar component to be loaded?

#### Type of change:
- 🐛 Bug Fix
- 🎨 Code Refactoring

### Changes Made:

- Refactor all error messages into `error-message.service.ts`
- Edit logger message in `phase.service.ts` to standardise format
- Add additional check for valid github repository when logging in for the first time before fetching data

### Screenshots:

https://github.com/CATcher-org/WATcher/assets/97519138/c9bbac02-b0a4-40e9-920e-89d4f4ce55a9

### Proposed Commit Message:

```
Standardise error messages for invalid repository names

Let's refactor all error messages to standardise them
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [ ] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [X] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

**Comment by joyngjr** [comment]
@luminousleek Hi, could I get your help to review this PR?

File: src/app/auth/session-selection/session-selection.component.ts [hunk 1]
```diff
@@ -85,6 +87,22 @@ export class SessionSelectionComponent implements OnInit {
...
+  }
+
+  /**
+   * Extracts the Data Repository Details from the input sessionInformation.
+   * @param sessionInformation - string in the format of 'orgName/dataRepo'
+   */
+  private getDataRepoDetails(sessionInformation: string) {
+    return sessionInformation.split('/')[1];
+  }
+
```
Comment (luminousleek) [inline src/app/auth/session-selection/session-selection.component.ts:105]: Not sure what this is for since it's not used?

File: src/app/auth/session-selection/session-selection.component.ts [hunk 2]
```diff
@@ -31,6 +32,7 @@ export class SessionSelectionComponent implements OnInit {
     private authService: AuthService,
     private repoUrlCacheService: RepoUrlCacheService,
     private errorHandlingService: ErrorHandlingService,
+    private githubService: GithubService,
```
Comment (luminousleek) [inline src/app/auth/session-selection/session-selection.component.ts:35]: Not sure why this service is injected when it isn't used?

**Review by luminousleek — CHANGES_REQUESTED** [review]
Generally looks good, thanks for refactoring all the error messages into a single service. 

I think you're trying to implement the extra check for repo validity in `session-selection.component.ts` now, but that should be in a separate PR.

There's also a bunch of linting changes but it looks ok to me. Maybe you can put that in your PR and commit message as well. 

Please also follow the commit message guidelines in https://se-education.org/guides/conventions/git.html

**Comment by joyngjr** [comment]
@luminousleek Thanks for your help! I've changed back to double quotation marks since it doesn't make a difference, and removed the unused code from when I tried a different implementation.

**Review by luminousleek — APPROVED** [review]
LGTM, thanks for your work!

**Comment by joyngjr** [comment]
@luminousleek I've modified the `codegen.yml` file to resolve merge conflicts. Could I get your help to review this PR again?

**Review by luminousleek — APPROVED** [review]
LGTM, sorry for the late review!
