### PR TITLE
Fix incorrect behaviour when filtering by assignee in issues with multiple assignees

### LINKED ISSUE #385: Incorrect filtering of issues with multiple assignees
**Describe the bug**
Bug from PR #381 , new assignee filter breaks when issues have more than one assignee

**To Reproduce**

1. Go to repository with an issue containing multiple assignees
1. Ensure the issues/PRs are currently grouped by assignees
1. Under assignee filter, select only one of the assignees for that issue
1. Notice that additional users and issues are shown, even if that user is not included in the assignee filter

**Expected behavior**
Only columns of users included in the assignee filter should be displayed.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: MS Edge
- Version: 127.0.2651.74

### PR DESCRIPTION
**Pull request by IzN432**
### Summary:

Fixes #385 

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Following @Eclipse-Dominator 's  [comments](https://github.com/CATcher-org/WATcher/pull/389#pullrequestreview-2589433090) on #389, added a check for if the group is found in the filters in `IssueDataTable`.

### Screenshots:

https://github.com/user-attachments/assets/efcb9f87-0f1b-4c26-a244-573815262385

### Proposed Commit Message:

```
Hide assignees not selected in filter

For issues with multiple assignees, having one of the assignees selected
in the filter displays all other assignees as groups.

This is misleading behaviour since the assignees that are not selected
are expected to be hidden.

Let's add a check for if the group is selected in the filter before
displaying the data.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [ ] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [ ] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

File: src/app/shared/issue-tables/IssuesDataTable.ts [hunk 1]
```diff
@@ -63,7 +65,25 @@ export class IssuesDataTable extends DataSource<Issue> implements FilterableSour
...
+          const groupFilterAsGithubUser = this.filter.assignees.map((selectedAssignee) => {
+            return GithubUser.fromUsername(selectedAssignee);
+          });
+          const groupFilterAsMilestone = this.filter.milestones.map((selectedMilestone) => {
+            return Milestone.fromTitle(selectedMilestone);
+          });
+
+          const isGroupInFilter =
+            groupFilterAsGithubUser.filter((githubUser) => this.group?.equals(githubUser)).length !== 0 ||
+            groupFilterAsMilestone.filter((milestone) => this.group?.equals(milestone)).length !== 0;
```
Comment (Eclipse-Dominator) [inline src/app/shared/issue-tables/IssuesDataTable.ts:78]:
```suggestion
            groupFilterAsGithubUser.some((githubUser) => this.group?.equals(githubUser)) ||
            groupFilterAsMilestone.some((milestone) => this.group?.equals(milestone));
```
This is not very efficient, `Array.some()` is built for this.

File: src/app/shared/issue-tables/IssuesDataTable.ts [hunk 2]
```diff
@@ -63,7 +65,25 @@ export class IssuesDataTable extends DataSource<Issue> implements FilterableSour
...
+
+          if (!isGroupInFilter) {
+            this.count = 0;
+            return [];
+          }
+
```
Comment (Eclipse-Dominator) [inline src/app/shared/issue-tables/IssuesDataTable.ts:84]: I'm not entirely convinced this is the best solution because it feels a bit hacky. However, I don't see an easier way to achieve this without changing the storage type of filter.

One way to improve this would be to encapsulate the logic into a separate function, like `isGroupInFilter(group: Group, filter: Filter)`. This would make the `map` more readable and less hacky.

File: src/app/core/models/github-user.model.ts [hunk 3]
```diff
@@ -52,6 +52,22 @@ export class GithubUser implements RawGithubUser, Group {
     Object.assign(this, rawData);
   }
 
+  static fromUsername(username: string) {
```
Comment (Eclipse-Dominator) [inline src/app/core/models/github-user.model.ts:55]: Might be useful to add a comment to explain why this method exists so other devs would the purpose of this function.

File: src/app/core/models/milestone.model.ts [hunk 4]
```diff
@@ -18,6 +18,10 @@ export class Milestone implements Group {
     this.number = milestone.number ? +milestone.number : undefined;
   }
 
+  static fromTitle(title: string): Milestone {
```
Comment (Eclipse-Dominator) [inline src/app/core/models/milestone.model.ts:21]: ditto.

**Review by Eclipse-Dominator — CHANGES_REQUESTED** [review]
Working as intended! Good work.

There are some slight refactoring and efficiency in your code.  Otherwise, LGTM!

**Comment by IzN432** [comment]
Made the changes!

**Review by Eclipse-Dominator — APPROVED** [review]
LGTM!

**Review by Arif-Khalid — APPROVED** [review]
Excellent change that effectively solves the issue in a structured, concise solution.
LGTM!
